# Generated by Django 2.0.3 on 2020-02-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categorytype',
            new_name='category_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='related',
        ),
        migrations.AddField(
            model_name='category',
            name='menu_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='addon_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='orders.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='addon_limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stylized_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
