# Generated by Django 2.0.3 on 2020-02-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200226_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'Small'), ('l', 'Large')], max_length=16, null=True),
        ),
    ]
