# Generated by Django 2.0.3 on 2020-02-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200227_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='addeditem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='addeditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_item', to='orders.MenuItem'),
        ),
    ]
