# Generated by Django 2.0.3 on 2020-03-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200301_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_time',
            field=models.DateTimeField(null=True),
        ),
    ]
