# Generated by Django 2.0.3 on 2020-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cart_ordered_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='finished',
        ),
        migrations.AddField(
            model_name='cart',
            name='delivered_time',
            field=models.DateTimeField(null=True),
        ),
    ]
