# Generated by Django 2.0.3 on 2020-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(choices=[('Mushrooms', '+ Mushrooms'), ('Green Peppers', '+ Green Peppers'), ('Onions', '+ Onions')], max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='sub',
            name='extraCheese',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub',
            name='extras',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
