# Generated by Django 2.0.3 on 2020-02-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pizzas',
            field=models.ManyToManyField(to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='cart',
            name='platters',
            field=models.ManyToManyField(to='orders.Platter'),
        ),
        migrations.AddField(
            model_name='cart',
            name='subs',
            field=models.ManyToManyField(to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='numberoftoppings',
            field=models.IntegerField(choices=[(0, 'Cheese'), (1, '1 Topping'), (2, '2 Toppings'), (3, '3 Toppings'), (4, 'Special Toppings')], default=0),
        ),
        migrations.AddField(
            model_name='sub',
            name='addextra',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
        migrations.RemoveField(
            model_name='sub',
            name='extras',
        ),
        migrations.AddField(
            model_name='sub',
            name='extras',
            field=models.ManyToManyField(to='orders.Extra'),
        ),
    ]
