# Generated by Django 2.0.3 on 2020-02-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200217_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='platters',
            field=models.ManyToManyField(blank=True, to='orders.Platter'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='primos',
            field=models.ManyToManyField(blank=True, to='orders.Primo'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subs',
            field=models.ManyToManyField(blank=True, to='orders.Sub'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.Extra'),
        ),
    ]
