# Generated by Django 2.0.3 on 2020-02-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200217_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='promotional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topping',
            name='toppingStylized',
            field=models.CharField(default='NOT NULL', max_length=64),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping',
            field=models.CharField(max_length=64),
        ),
    ]
