# Generated by Django 2.0.3 on 2020-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200217_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='extraStylized',
            field=models.CharField(default='NOT NULL', max_length=64),
        ),
        migrations.AddField(
            model_name='extra',
            name='promotional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extra',
            name='extra',
            field=models.CharField(max_length=64),
        ),
    ]
